INSERT INTO product (name, description, price) VALUES 
('Água', 'Água mineral sem gás 500ml', 2.00),
('Coca Cola 2L', 'Refrigerante Coca-Cola de 2 litros', 8.00),
('Pizza', 'Pizza grande de calabresa com queijo', 40.00),
('Leite', 'Leite integral UHT 1 litro', 7.00),
('Arroz', 'Arroz branco tipo 1 pacote de 1kg', 5.00),
('Playstation', 'Console PlayStation 5 Slim com controle', 5000.00),
('Cuscuz', 'Flocão de milho para cuscuz 500g', 1.00),
('Feijão', 'Feijão carioca tipo 1 pacote de 1kg', 8.00),
('Macarrão', 'Macarrão espaguete 500g', 4.50),
('Açúcar', 'Açúcar refinado pacote de 1kg', 6.00),
('Café', 'Café torrado e moído pacote de 500g', 15.00),
('Óleo de Soja', 'Óleo de soja refinado garrafa de 900ml', 9.00),
('Manteiga', 'Manteiga com sal pote de 200g', 12.00),
('Queijo Mussarela', 'Queijo mussarela fatiado 1kg', 35.00),
('Presunto', 'Presunto cozido fatiado 1kg', 28.00),
('Pão Francês', 'Pão francês unidade', 0.80),
('Refrigerante Lata', 'Refrigerante lata 350ml', 5.00),
('Suco de Laranja', 'Suco de laranja integral 1 litro', 9.00),
('Chocolate', 'Barra de chocolate ao leite 90g', 7.50),
('Biscoito Recheado', 'Biscoito recheado sabor chocolate 140g', 4.00),
('Detergente', 'Detergente líquido neutro 500ml', 3.50),
('Sabão em Pó', 'Sabão em pó para roupas pacote de 1,6kg', 18.00),
('Papel Higiênico', 'Papel higiênico folha dupla pacote com 12 rolos', 22.00),
('Shampoo', 'Shampoo para todos os tipos de cabelo 400ml', 19.00),
('Creme Dental', 'Creme dental com flúor 90g', 8.00),
('Escova de Dentes', 'Escova de dentes com cerdas macias', 10.00),
('Banana', 'Banana prata 1kg', 6.00),
('Maçã', 'Maçã gala 1kg', 9.00),
('Ovo Cartela', 'Cartela com 30 ovos brancos', 20.00);